### ISSUE TITLE
Determine Best NLP Model for Our Project

### ISSUE THREAD

**Issue by yalmanzade** [DJT777/CS478-LinguisAquilis#18]
Investigate current research on Artificial Intelligence that can vectorize human language. Consider methods using Recurrent Neural Networks and Transformers as neural network models. Vectorize enter JSON dataset of USI courses with embeddings into the data structure of the University of Southern Indiana registrar's catalog of courses available to students of the university.

**Comment by DJT777** [comment]
Universal Sentence Encoder was our choice
